# Generated by Django 5.0.4 on 2024-06-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_exercise_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='neme',
            new_name='name',
        ),
    ]
