# Generated by Django 5.0.4 on 2024-07-12 11:23

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_alter_book_author_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_title', models.CharField(max_length=100)),
                ('energy', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Flash Hero',
            },
            bases=(models.Model, main_app.models.RechargeEnergyMixin),
        ),
        migrations.CreateModel(
            name='SpiderHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_title', models.CharField(max_length=100)),
                ('energy', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Spider Hero',
            },
            bases=(models.Model, main_app.models.RechargeEnergyMixin),
        ),
    ]
